#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

// composer autoloader
require __DIR__ . '/vendor/autoload.php';

// custom yii classmap
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

// load helper stuff
require __DIR__ . "/lib/helper_functions.php";

// require console preloader
require __DIR__ . "/lib/console_preload.php";

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
